### ISSUE TITLE
Extension does not know how to serialize a BigInt

### ISSUE THREAD

**Issue by rmnldwg** [silx-kit/vscode-h5web#15]
### Describe the bug

When I store an integer as an attribute to e.g. a dataset in an HDF5 file, the H5Web extension does not display any attributes, but prints in red `Do not know how to serialize a BigInt`.

### To Reproduce

1. Select the HDF5 file in VS Code explorer
2. Go to the dataset/group that has an integer as an attribute
3. Click on "inspect" in the top right corner
4. Scroll down to the **Attributes** section
5. See error --> Instead of the attributes, the extension shows `Do not know how to serialize a BigInt` in red.

I have created a tiny [Python script](https://gist.github.com/rmnldwg/aaf6f2cd0f1d5da0b29bf4e920eed375) that creates an HDF5 file that - when displayed in the VS code extension - leads to the described bug.

Here's also the resulting HDF5 file zipped: [h5web_bug.zip](https://github.com/silx-kit/vscode-h5web/files/9351939/h5web_bug.zip)

### Expected behaviour

I would expect to see the attributes, instead of the error message.

### Screenshots

![2022-08-16](https://user-images.githubusercontent.com/48687784/184903325-5d86b961-8194-4d6a-9489-8725ae929bc9.png)

### Context

- OS: Ubuntu 20.04 (WSL2)
- VS Code version: 1.70.1
- Extension version: 0.0.4

**Comment by loichuder** [comment]
Hello @rmnldwg, thanks for raising the issue, even more so for providing a way to reproduce it !

I recently added support for `int64` for dataset values (https://github.com/silx-kit/h5web/pull/1179) so it should be quite simple to do the same for attribute values.

Expect this to be fixed in the next release :slightly_smiling_face:

**Comment by rmnldwg** [comment]
Amazing, thanks for the info!

Great extension by the way, it makes my job so much more seamless 👍🏻

**Comment by axelboc** [comment]
Hi @rmnldwg, the issue should now be fixed in v0.0.5. Please let us know if that's not the case 😉

**Comment by axelboc** [comment]
Re-opening as per https://github.com/silx-kit/vscode-h5web/issues/30
